### ISSUE TITLE
Deployment fails with unresolved dependency when UnsubscribeOnDelete is not set

### ISSUE THREAD

**Issue by eoinsha** [lumigo-io/SAR-Logging#19]
Received this error from CloudFormation
```
Embedded stack arn:aws:cloudformation:eu-west-1:*******:stack/logging-service-dev-autoSubscribeLogGroupsStream-****was not successfully created: Template format error: Unresolved resource dependencies [UnubscribeExistingLogGroups] in the Resources block of the template
````

with the following resource declaration in Serverless YML.

```
autoSubscribeLogGroupsFirehose:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/auto-subscribe-log-group-to-arn
      SemanticVersion: 1.11.0
    Parameters:
      DestinationArn: !GetAtt logFirehoseStream.Arn
      Prefix: '/aws/lambda/'
      Tags: SLIC_STAGE=${self:provider.stage}
      FilterName: forward-logs
```
